### ISSUE TITLE
Support for installing from nest.land

### ISSUE THREAD

**Issue by xpyxel** [harmonyland/harmony#109]
**What do you want to request?**
The ability to install from [nest](https://nest.land) would be nice as alternative along side being able to install from [/x/](https://deno.land/x) and the GitHub repository itself.

**Do you have anything to tell us about your request?**
Nest provides a block-chain backed immutable registry for deno modules, adding support for it is as simple as creating an account and using their [cli](https://docs.nest.land/eggs) to link an api key and initialize a package file which contains information specifically for their registry and nothing else. An example of the package file it uses can be seen [here](https://gitlab.com/hanna/proton/-/blob/dev/egg.json) on a package I'm working on currently that is using harmony itself as well.

**Comment by Helloyunho** [comment]
Harmony is now available at [nest.land](https://nest.land/package/harmony) too! Thanks!
