### ISSUE TITLE
[Bug] Cannot fetch an emoji.

### ISSUE THREAD

**Issue by Ayfri** [harmonyland/harmony#112]
**What's the bug?**
Hi!
I try to react with an emoji but I get an error that is way too strange to not be a bug.
My code :
```ts
[imports]
const WAIT_EMOJI = '813551205283790889';
const LABS_TS = '507389389098188820';

class MyCommand extends Command {
	[...]

	public async execute(ctx: CommandContext): Promise<void> {
		ctx.message.addReaction(await ctx.client.emojis.fetch(LABS_TS, WAIT_EMOJI));
	}
}
```
The error :
```ts
error: Uncaught (in promise) DiscordAPIError: {
  url: "https://discord.com/api/v8/channels/620663106250604546/messages/818225520994549840/reactions/%3Ca:wa...",
  status: 400,
  method: "PUT",
  code: 50035,
  message: "Invalid Form Body",
  errors: {
    emoji_id: [
      {
        code: "NUMBER_TYPE_COERCE",
        message: 'Value "813551205283790889>" is not snowflake.'
      }
    ]
  },
  requestData: {
    headers: {
      "User-Agent": "DiscordBot (harmony, https://github.com/harmony-org/harmony)",
      Authorization: "Bot ODAxOTc0NTIxMTMzMjY5MDUz.YAoe-Q.is9H6QQgGmxMIyBdS3YB5PWCTF8"
    },
    body: undefined,
    method: "PUT"
  }
}
      reject(new DiscordAPIError(Deno.inspect(error), error))
             ^
    at RESTManager.handleStatusCode (https://deno.land/x/harmony@v1.1.2/src/models/rest.ts:500:14)
    at Object.onComplete (https://deno.land/x/harmony@v1.1.2/src/models/rest.ts:577:22)
    at async https://deno.land/x/harmony@v1.1.2/src/models/rest.ts:249:30

Process finished with exit code 1

```

**What should have happened?**
Fetch the emoji and react with it.

**What is actually happening?**
Crash because it searched the emoji with the ID + `>`, and the link strangely finish with `<a:wa`, but the emoji is `<a:wait:813551205283790889>`.

**What versions you're using?**
 - OS: Windows 10 (21H1 Bêta, version 19043.844)
 - Deno: Deno 1.8.0
 - Harmony: Latest (1.1.2)

**Do you have anything to tell us more about the bug?**
This should be better documented, with [typedoc](https://github.com/TypeStrong/typedoc) for example.

**Comment by DjDeveloperr** [comment]
Thanks for reporting this bug! I'll make a PR in a bit to fix this. I checked discord docs, emoji has to be URL encoded from `<name>:<id>` and not the emoji string but its currently done wrong .-.
