### ISSUE TITLE
[Feature Request] Add try/catch for `execute`, `beforeExecute` & `afterExecute` methods.

### ISSUE THREAD

**Issue by Ayfri** [harmonyland/harmony#114]
**What do you want to request?**
Add a `try/catch` to these methods because it's really annoying to get your bot down when you do something wrong, or having an error but because you didn't put `try/catch`, nothing is sent in the console.

**Do you have anything to tell us about your request?**
Almost every command handler does this!
You could also add an `error` method in the command class (I think that it's weird to use the client to catch these).

**Comment by DjDeveloperr** [comment]
Errors from `beforeExecute`, `execute` and `afterExecute` are already handled in command handler's try-catch. `commandError` event is emitted when any of these errors containing both Command Context and Error. (I'm not sure if I understood it correctly)

**Comment by Ayfri** [comment]
Ah ?
But when I get an error from the execute method, the entire bot shuts down, is this normal thus ?

**Comment by DjDeveloperr** [comment]
Is the error from un-awaited Promise? Cause they're not catched in try/catch

**Comment by Ayfri** [comment]
I was getting errors from discord with trying to react with a custom emoji (I don't know if a fix exists now by the way) that was crashing everything.

Also, I've made this issue because when something sync fails (like sending an empty message), nothing is emitted in the console by default, which is very counterintuitive.

**Comment by DjDeveloperr** [comment]
> nothing is emitted in the console by default, which is very counterintuitive.

Well yeah I agree, we can possibly write those errors to console if there's no listener for `commandError` event.

> I was getting errors from discord with trying to react with a custom emoji (I don't know if a fix exists now by the way) that was crashing everything.

Did you await the `addReaction` method?

**Comment by Ayfri** [comment]
No.

**Comment by DjDeveloperr** [comment]
You have to await Promises for rejections to be caught.

**Comment by Ayfri** [comment]
Okay, I'll await these so, thanks for the response !

**Comment by Helloyunho** [comment]
Seems like it's solved! I'll close this right now.
