### ISSUE TITLE
[Feature Request] Add Unit Tests

### ISSUE THREAD

**Issue by Helloyunho** [harmonyland/harmony#125]
**What do you want to request?**
Adding unit tests

**Do you have anything to tell us about your request?**
Currently, harmony doesn't have any unit tests, which can make tests so much better and reliable.

**Comment by minseo0388** [comment]
https://docs.microsoft.com/ko-kr/visualstudio/javascript/unit-testing-javascript-with-visual-studio?view=vs-2019&tabs=mocha

**Comment by DjDeveloperr** [comment]
Deno has built in test runner.

**Comment by MierenManz** [comment]
With unit tests you mean a set of tests that use the discord api right? I think we could easily look at discordeno's implementation and use that as a reference point

**Comment by DjDeveloperr** [comment]
Yes, using the Discord API itself. It won't be hard to come up with our own implementation.

**Comment by MierenManz** [comment]
It won't be hard no. But it's handy to have a reference point. We shouldn't be leaking resources or ops like dd does tho.

**Comment by DjDeveloperr** [comment]
> We shouldn't be leaking resources or ops like dd does tho.

This is not possible for Discord bots unit testing. We can't reopen connection for each test, that's just a very easy to hit rate limits...

**Comment by MierenManz** [comment]
If you create the resource before the tests and not close it in the test then it works normally. It will only show a "leak" when you close it in the test

**Comment by HippoBaguette** [comment]
> > We shouldn't be leaking resources or ops like dd does tho.
> 
> This is not possible for Discord bots unit testing. We can't reopen connection for each test, that's just a very easy to hit rate limits...

Why not run the tests with github actions, and pass resources as a secret, and then a command line argument? Then load all the tests into a runner which is ran with `deno run runner.ts TOKEN`

Or is this just not viable?

**Comment by MierenManz** [comment]
Resources are the things in the resource table. Not tokens etc.

Stuff that is in `Deno.resources()` like files, child processes and other things. Ops are the interactions between Rust and JavaScript. So leaking those means that some of those interactions didn't finish when the test finished.

**Comment by MierenManz** [comment]
> This is not possible for Discord bots unit testing. We can't reopen connection for each test, that's just a very easy to hit rate limits...

This is certainly possible. When trying to fix op + resource leaks in dd I found that their code only leaked them. Not the test code. So it's doable by alot

**Comment by DjDeveloperr** [comment]
As this will be taken care of in v3, should this issue be closed? (can be tracked in #225 instead)

**Comment by MierenManz** [comment]
All new functions would need their own tests. So maybe add a comment to #225 and say that all functions require a test etc.
Then I guess we can close this yeah
