### ISSUE TITLE
[Request] Add More Examples

### ISSUE THREAD

**Issue by Helloyunho** [harmonyland/harmony#126]
**What do you want to request?**
Adding more examples

**Do you have any solutions?**
If you have, please tell us so we can add(or at least think about) your solution!

Since we have lots of bot codes in `test/`, we might just need to change some and put them into the example.

**Do you have anything to tell us about your request?**
Right now harmony is getting known to many peoples and some junior coders can be confused if there are not enough examples.

**Comment by minseo0388** [comment]
i think it will be better if we post more examples on official instructions https://github.com/harmonyland/harmonyland.github.io

**Comment by minseo0388** [comment]
it will be better adding examples both in file and harmony.mod.land

**Comment by ZiomaleQ** [comment]
I think we could add examples on:
- Threads ( creating, joining, reading messages, getting a list of (active) threads )
- Message components ( Creating, responding to click )
- Simple permission check, for example, command that checks if a user has an admin
- Interaction response ( how to work with responses, for example MESSAGE_UPDATE type)
