### ISSUE TITLE
[Feature Request] Remove as many `any` types from code

### ISSUE THREAD

**Issue by MierenManz** [harmonyland/harmony#141]
The title should explain everything
We should strive to get as much types known and if necesarry use `unknown`
This will allow us to find type error's and bug related to typeErrors alot easier

**Comment by minseo0388** [comment]
i agree with this

**Comment by MierenManz** [comment]
It should only be used as last resort. Thus I think it's better to spend the time making interfaces and types for it for better intelisense aswell
