### ISSUE TITLE
[Tools] out with Eslint in with Deno lint

### ISSUE THREAD

**Issue by MierenManz** [harmonyland/harmony#158]
Like the title says. Now that camel case is removed.
We can easily work on switching out eslint for deno lint

This will likely be done in v3 rather than in v2

**Comment by minseo0388** [comment]
good idea..

**Comment by MierenManz** [comment]
This will be done in v3
the v2 pr for it closed 
ref: #201

**Comment by DjDeveloperr** [comment]
As this will be done in v3 now, and the PR is closed, I'll close this issue as well.
