### ISSUE TITLE
[Question] TS2367 [ERROR] when trying to cache harmony. Am I doing something wrong?

### ISSUE THREAD

**Issue by HippoBaguette** [harmonyland/harmony#176]
**What question do you have?**
Why is this error occurring? Have I done something wrong?
```ts
/*
deps.ts
*/
import { Client, Message} from 'https://deno.land/x/harmony/mod.ts';
```
then I run `deno cache`

```
error: TS2367 [ERROR]: This condition will always return 'false' since the types 'SlashCommandOptionType' and '0' have no overlap.
      type === 0 || type === 1
      ~~~~~~~~~~
    at https://deno.land/x/harmony@v2.0.0-rc2/src/interactions/slashCommand.ts:117:7
```

**Comment by MierenManz** [comment]
The recent update of deno included the new version of TypeScript.
Which broke the code for rc2.
This is already fixed on Github main branch, just not released to deno.land/x

In the meantime you could either downgrade back to deno 1.10 or use the github main branch

**Comment by HippoBaguette** [comment]
Alright thanks, I'm going to use the `main` branch now

**Comment by MierenManz** [comment]
@DjDeveloperr or @Helloyunho
Do we want to keep this issue open until the fix pas landed on stable?
Just for visibility.
