### ISSUE TITLE
[Bug] messageUpdate event has no guild

### ISSUE THREAD

**Issue by orvit-png** [harmonyland/harmony#194]
**What's the bug?**
In the event `messageUpdate`, if you grab the `guild` from newMessage, it will return null.

**How do we reproduce it?**
1. `if (!msg.guild) return;` in `messageUpdate`. Will return when msg is newMessage.
2. `if (!msg.guildID) return;` in `messageUpdate`. WIll not return when msg is newMessage.

**What should have happened?**
The guild object would be returned.

**What is actually happening?**
We gain the ever growing collectors item called 'null'.

**What versions you're using?**
 - OS: Arch x86_64
 - Deno: 1.11.3
 - Harmony: 2.0.0rc3

**Comment by DjDeveloperr** [comment]
Can you try from `main` branch for once? I think it's been fixed but not released

**Comment by orvit-png** [comment]
Didn't think to try that @DjDeveloperr, thanks for the suggestion. Fixed my problem.

**Comment by orvit-png** [comment]
@DjDeveloperr found a new problem out of this, gonna make a new issue.
