### ISSUE TITLE
[Bug] messageUpdate event does not contain member

### ISSUE THREAD

**Issue by orvit-png** [harmonyland/harmony#195]
**What's the bug?**
In the event `messageUpdate`, if you grab the `guild` from newMessage, it will return null.

**How do we reproduce it?**
1. `if (!msg.member) return;` in `messageUpdate`. Will return when msg is newMessage.

**What should have happened?**
The member object would be returned.

**What is actually happening?**
We gain the ever growing collectors item called 'null'.
![image](https://user-images.githubusercontent.com/55005263/124423619-217b6800-dd2b-11eb-9899-39d62a6c9cd4.png)

**What versions you're using?**
 - OS: Arch x86_64
 - Deno: 1.11.3
 - Harmony: 2.0.0rc3

*using the main branch*

**Comment by orvit-png** [comment]
poggers `const msgMember = msg.guild.members.get(msg.author.id);`

**Comment by DjDeveloperr** [comment]
try from latest commit

**Comment by orvit-png** [comment]
damn dj fixing everyone's shit
