### ISSUE TITLE
[Feature Request] Allow local paths for embed images

### ISSUE THREAD

**Issue by Blocksnmore** [harmonyland/harmony#196]
**What do you want to request?**

Add the ability to use local file paths ie: `./pepega.png` inside of Embed images

**Do you have anything to tell us about your request?**

Don't believe so

**Comment by DjDeveloperr** [comment]
You can already do that, look into `MessageAttachment`'s docs and `Embed#attach`.

**Comment by DjDeveloperr** [comment]
Adding on that, though its a bit unclear how to link the attachment to a Embed property. For that, you have to use `attachment://filename.ext` as the URL.
