### ISSUE TITLE
[Bug/API issue] Missing fields on ThreadChannel objects

### ISSUE THREAD

**Issue by ashisbored** [harmonyland/harmony#208]
**What's the bug?**
[According to the Discord API docs](https://discord.com/developers/docs/topics/threads#new-thread-fields), `ThreadChannel`s should have access to the id of the user who created the thread as the field `owner_id` (repurposed from group DM channels) along with the slowmode setting of the thread (`rate_limit_per_user`), however harmony doesn't appear to expose these field in any way and they are not included in the lower-level `ThreadChannelPayload` interface either.

**Comment by MierenManz** [comment]
I assume that this is because the pr for threads was quite old and threads have changed in the meantime.
This will likely be fixed soon.

**Comment by DjDeveloperr** [comment]
Fixed with #209
