### ISSUE TITLE
[Bug]  Message.addReaction() crashes.

### ISSUE THREAD

**Issue by Muha0644** [harmonyland/harmony#216]
**What's the bug?**
`Message.addReaction()` crashes with of http error 411 when sending an emoji. 

**How do we reproduce it?**
use `Message.addReaction("flushed")` (same if you specify ":᠎flushed:").

**What should have happened?**
Instead of sending a reaction to the message, the it crashes deno completely. 

**What is actually happening?**
```error: Uncaught (in promise) DiscordAPIError: 
PUT https://discord.com/api/v9/channels/*number*/messages/*another number*/reactions/flushed/@me returned 411
(unknown) undefined
      throw new DiscordAPIError({
            ^
    at BucketHandler.execute (https://deno.land/x/harmony@v2.0.0/src/rest/bucket.ts:217:13)
    at async BucketHandler.push (https://deno.land/x/harmony@v2.0.0/src/rest/bucket.ts:51:14)
    at async RESTManager.make (https://deno.land/x/harmony@v2.0.0/src/rest/manager.ts:236:12)
    at async RESTManager.put (https://deno.land/x/harmony@v2.0.0/src/rest/manager.ts:339:12)
    at async GuildTextChannel.addReaction (https://deno.land/x/harmony@v2.0.0/src/structures/textChannel.ts:90:5)
```

**What versions you're using?**
 - OS: Arch Linux (btw)
 - Deno: 1.13.0
 - Harmony: 2.0.0

**Do you have anything to tell us more about the bug?**
Mozilla docs say 411 means Length Required. I'm 90% sure i'm using the method right because this is a http error, not a TS or Deno error.

**Comment by DjDeveloperr** [comment]
`addReaction` only works with unicode for default emoji.

**Comment by MierenManz** [comment]
Maybe we should see if we can make it work with aliases like `:joy:` etc.

**Comment by Muha0644** [comment]
But discord doesn't use unicode emoji, it uses aliases just like github on markdown. when I type : flushed : it turns into :flushed: .
Another thing, if you add a plus before it like +: flushed: it automatically becomes a reaction, not a new message. The bot does not do this, it sends the message with a plus and an emoji. This is not a problem, just an observation.

The problem is you can't send custom emojis as reactions with this. Eg. if a server has a :troll: emoji, you can't send it as a reaction using harmony.

**Comment by MierenManz** [comment]
Every custom emote is formatted as `:guildid:name:` or `:name:guildid:`
So that is how you would send custom emoji's.
Not sure how harmony goes with this. But I assume that that works

**Comment by Muha0644** [comment]
> Every custom emote is formatted as `:guildid:name:` or `:name:guildid:` iirc.
> So that is how you would send custom emoji's.
> Not sure how harmony goes with this. But I assume that that works

Just tested it out, neither `:guildid:name:` `nor :name:guildid:` send the emoji, just the text. Just using `:name:` also does nothing.

**Comment by 6days9weeks** [comment]
> Every custom emote is formatted as `:guildid:name:` or `:name:guildid:` iirc.
> So that is how you would send custom emoji's.
> Not sure how harmony goes with this. But I assume that that works

It's just `<:AquaCry:784740386680733716>` emote name and snowflake.

**Comment by 6days9weeks** [comment]
> But discord doesn't use unicode emoji, it uses aliases just like github on markdown. when I type : flushed : it turns into 😳 .
> Another thing, if you add a plus before it like +: flushed: it automatically becomes a reaction, not a new message. The bot does not do this, it sends the message with a plus and an emoji. This is not a problem, just an observation.
> 
> The problem is you can't send custom emojis as reactions with this. Eg. if a server has a :troll: emoji, you can't send it as a reaction using harmony.

Don't think bots have the +emoji shortcut.

**Comment by grian32** [comment]
Custom emojis are sent with `<:troll:750129788332802080>` and `troll` being the emojiname, `750129788332802080` being the id, and animated emojis sent with `<a:wuthead:867501649966268476>`, and regular emojis with their unicode variants, a bot is not a markdown textbox, please inform yourself on the internals of discord before making bug reports as no other framework does this.

**Comment by Muha0644** [comment]
> > But discord doesn't use unicode emoji, it uses aliases just like github on markdown. when I type : flushed : it turns into flushed .
> > Another thing, if you add a plus before it like +: flushed: it automatically becomes a reaction, not a new message. The bot does not do this, it sends the message with a plus and an emoji. This is not a problem, just an observation.
> > The problem is you can't send custom emojis as reactions with this. Eg. if a server has a :troll: emoji, you can't send it as a reaction using harmony.
> 
> Don't think bots have the +emoji shortcut.

Yeah they don't, it just sends the + as a message. the + thing is a feature of the discord app.

**Comment by Muha0644** [comment]
> Custom emojis are sent with `<:troll:750129788332802080>` and `troll` being the emojiname, `750129788332802080` being the id, and animated emojis sent with `<a:wuthead:867501649966268476>`, and regular emojis with their unicode variants, a bot is not a markdown textbox, please inform yourself on the internals of discord before making bug reports as no other framework does this and it would be a lot of unnecessary work. And discord does use unicode emojis, aliases just turn the text into its unicode emote, put `\` before any emote to get its unicode variant

What exactly to you mean by "id"? id of the user? server id? because the server id doesn't work. When I do what you said it sends the :troll: but without the "id". Yes, i'm not stupid, I changed the id to the server's id.

Also how am I supposed to know that? Should i go apply to be a developer at discord so I can make some shitty ass bot that replies with sus to every message? I assumed how discord works because when i specify an alias in  `Message.reply()`, it sends it as an emoji. This only worked with default emojis, not with custom ones. The `addReaction()` method did not work with any aliases.

This is still a problem, because the documentation (if you can even call it a decumentation) says absolutely nothing. The automatic tooltip just said `string | Emoji type`, so i obviously assumed it expects an alias as a string or an emoji, as any normal person would. If you want to do anything useful you have to read the code of harmony because it's ~poorly~ not documented.

**Comment by grian32** [comment]
> What exactly to you mean by "id"? id of the user? server id? because the server id doesn't work. When I do what you said it sends the :troll: but without the "id". Yes, i'm not stupid, I changed the id to the server's id.

The emoji's id.

> Also how am I supposed to know that? Should i go apply to be a developer at discord so I can make some shitty ass bot that replies with sus to every message? I assumed how discord works because when i specify an alias in Message.reply(), it sends it as an emoji. This only worked with default emojis, not with custom ones. The addReaction() method did not work with any aliases.

Read Discord's API docs, they dont exist so you can come here and complain: https://discord.com/developers/docs/reference#message-formatting

> This is still a problem, because the documentation (if you can even call it a decumentation) says absolutely nothing. The automatic tooltip just said string | Emoji type, so i obviously assumed it expects an alias as a string or a unicode emoji, as any normal person would. If you want to do anything useful you have to read the code of harmony because it's poorly not documented.

While I agree that is an issue with harmony, which will be getting greater focus with the v3 rewrite, we do not need to repeat Discord's API Docs.

**Comment by Muha0644** [comment]
How did I not see this before? Thank you for the link, this looks very useful. All i could find is docs for other frameworks. 
I completely forgot discord is a webapp and that you could just inspect element...

Also you _do_ know the whole point of bug reports it to complain? Deno crashed when I tried to send an alias, that is a bug. At least i would consider it a bug, since it literally crashed. You need to take a break man, I can see something is bothering you (maybe school starting soon?) because you seem agitated. I asked for help and you have a problem with that. Well whatever is bothering you, I hope it ends well.

Good luck with the v3 rewrite, hopefully it's gonna be great!

**Comment by DjDeveloperr** [comment]
This is (unfortunately) default behavior of JavaScript to crash on unhandled (promise) rejections. So you'll have to either await it and catch in a try/catch block, or `.catch(...)` it

**Comment by grian32** [comment]
> Also you do know the whole point of bug reports it to complain? Deno crashed when I tried to send an alias, that is a bug. At least i would consider it a bug, since it literally crashed. 

The whole point of bug reports is to report bugs/flaws in a program, this is clearly not a fault in Harmony as you used it wrong, would you say me writing 
```
consol.log("hi")
```
and then Deno crashing is a bug in Deno? No, it's a bug in my code, same situation here

**Comment by DjDeveloperr** [comment]
Original issue is answered, if you have additional suggestion please open a new issue.

**Comment by Muha0644** [comment]
> This is (unfortunately) default behavior of JavaScript to crash on unhandled (promise) rejections. So you'll have to either await it and catch in a try/catch block, or `.catch(...)` it
> 
> Aliases resolving emoji names to unicode are not included because it would quite significantly increase the size of the package for something all may not even use. However, you can easily get unicode for emojis by adding a backslash before the emoji in Discord.

That's not really an issue, but custom emotes don't have unicode entries. You can't react with custom emotes with harmony like you can on the app.

**Comment by DjDeveloperr** [comment]
For custom emotes you can either pass Emoji object, use the `<a?:name:id>` format or just `name:id` (note: this format only applies to reactions as per Discord docs).

**Comment by Muha0644** [comment]
> > Also you do know the whole point of bug reports it to complain? Deno crashed when I tried to send an alias, that is a bug. At least i would consider it a bug, since it literally crashed.
> 
> The whole point of bug reports is to report bugs/flaws in a program, this is clearly not a fault in Harmony as you used it wrong, would you say me writing
> 
> ```
> consol.log("hi")
> ```
> 
> and then Deno crashing is a bug in Deno? No, it's a bug in my code, same situation here

Wait, you program without an IDE? Because an IDE would definitely tell you about the error. What I did threw a http error, not a logic error. The IDE did not say anything was wrong with my code. Anyway, since i have the docs and some advice I think I can make something work. I don't usually do typescript, I'm a C++ kind of guy. Everyone tells me C++ is dying and I can't get a job with it but I still like it for it's performance.

Thanks for the help everyone. Again, good luck with v3!
