### ISSUE TITLE
[Bug] createOauthURL Scope Issue

### ISSUE THREAD

**Issue by Setherizor** [harmonyland/harmony#270]
**What's the bug?**
When using the function [createOauthURL](https://github.com/harmonyland/harmony/blob/6d7786dcd09b7474607248a7582e726920d7624b/src/utils/oauthURL.ts#L17), the scopes are not converted into params correctly, making the url unusable.

**How do we reproduce it?**
```ts
const url = createOAuthURL({
    clientID: 'XXX',
    scopes: ['bot','applications.commands'],
    redirectURI: 'XXX',
  });
```

**What should have happened?**
Scope param should have looked like: `scope=bot%20applications.commands`

**What is actually happening?**
```ts
url == "https://discord.com/api/9/oauth2/authorize?client_id=XXX&scopes=%5Bobject+Set%5D&permissions=0&redirect_uri=XXX"
```

**What versions you're using?**
 - OS: Ubuntu 21.04
 - Deno: 1.16.2
 - Harmony: v2.3.0

**Do you have anything to tell us more about the bug?**
Same thing behaivor in a browser:
```js
[new Set([1,1,2])].join(' ')
> '[object Set]'
```

One approach to fix this is by using something like
```ts
        scopes: Array.from(new Set([1,1,2])).join(' ')
```
[for line 23](https://github.com/harmonyland/harmony/blob/6d7786dcd09b7474607248a7582e726920d7624b/src/utils/oauthURL.ts#L23)

---
Might be the wrong place to add this, but are there any plans to add in more options for supporting oauth2 like [params for the `/authorize` endpoint](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant) or a way to interact with [the `/token` endpoints](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant-access-token-exchange-example)?

**Comment by DjDeveloperr** [comment]
Yep, there are plans to add more OAuth2 support. It would be great if you could make a new tracking issue for that
