### ISSUE TITLE
[Bug] Webhook issues

### ISSUE THREAD

**Issue by Oliver-makes-code** [harmonyland/harmony#273]
**What's the bug?**
Currently, webhooks have a couple problems:
1. Files are unable to be sent via webhooks.
2. ~~The Webhook constructor accesses `this.client` before it's assigned.~~ Fixed in PR #274 
3. ~~There's no proper way to fetch a Webhook from a channel without making direct API requests.~~ Fixed in PR #274 

With 2, it can be as easy as assigning `this.client` at the beginning of the constructior, with 3, a `TextChannel$fetchWebhooks` method could be added, and 1 has a more in-depth solution that I haven't figured out yet.

**Comment by DjDeveloperr** [comment]
Files can already be sent, just that sending multiple files is not supported at the moment. Take following example:
```ts
const hook = await Webhook.fromURL(Deno.env.get('WEBHOOK')!)
await hook.send({
  file: await MessageAttachment.load(
    'https://cdn.discordapp.com/emojis/783639203153575948.png?size=96'
  )
})
```
