### ISSUE TITLE
[Bug] Accessing `interaction.subCommand` or `interaction.subCommandGroup` appears to freeze code.

### ISSUE THREAD

**Issue by vxern** [harmonyland/harmony#280]
**What's the bug?**
Accessing `interaction.subCommand` or `interaction.subCommandGroup` on an `ApplicationCommandInteraction` which has neither of those will cause them to not yield a value, thus freezing execution of code following them.

**How do we reproduce it?**
Create a stand-alone command without sub-commands or sub-command groups and, when handling a call to it, access `interaction.subCommand` or `interaction.subCommandGroup`.

**What should have happened?**
`undefined` should be yielded, regardless of whether the interaction has subcommands or not.

**What is actually happening?**
No value is yielded, and the code appears to freeze.

**What versions you're using?**
 - OS: Linux
 - Deno: v1.15.2
 - Harmony: v2.4.0

**Comment by DjDeveloperr** [comment]
It freezing sounds strange. Do you have a handler for `interactionError`? If not try adding this:
```ts
client.interactions.on("interactionError", console.error);
```

**Comment by vxern** [comment]
I did not have a handler for `interactionError`, but now that I've added it, I got a `TypeError`: `Cannot read properties of undefined (reading '0')`. This is raised within the `subCommand` getter on `ApplicationCommandInteraction`.

**Comment by DjDeveloperr** [comment]
Ok so this is a bug on Harmony's part, it should be using optional chaining here

**Comment by vxern** [comment]
I understand. Thank you for the fast response :)

**Comment by DjDeveloperr** [comment]
Can you check if this bug still occurs on `https://code.harmony.rocks/fix-appcmd-getter`? (you can change import URL to this, it maps to GitHub branch)

**Comment by vxern** [comment]
It still raises the same `TypeError` at line `76` column `24`.

**Comment by DjDeveloperr** [comment]
Should be fixed on e135114 now. Try `https://code.harmony.rocks/e135114`

**Comment by vxern** [comment]
It works :) Lovely.

**Comment by vxern** [comment]
It works now :+1:
