### ISSUE TITLE
[Feature Request] Add support for optional arguments.

### ISSUE THREAD

**Issue by mmeyer429** [harmonyland/harmony#290]
**What do you want to request?**
Add support for optional arguments.

Currently if you call a command with less arguments than the amount of arguments specified it emits a message of missing arguments and stops unless you have an `onMissingArgs` function defined.

As a work around you can call execute from `onMissingArgs` but that removes the before/after Execute and middleware calls. 

**Do you have any solutions?**
As an Idea I would convert the arguments results into Objects that can keep track if they actually `matched` something, if they are `optional` and if they are valid, meaning something like `valid() {return this.matched || this.optional )

With that you can grab the list of arguments and do something like `parsedArgs.every((arg) => arg.valid()` and use that to validate if there are missing arguments.

On another note, if there are missing arguments no middleware's are run at all which caused me some confusion on why my command was not even getting called when an argument was missing, which is not the case when you have more values than arguments.

**Do you have anything to tell us about your request?**

**Comment by MierenManz** [comment]
I think it would also be possible to set args that are not supplied to `null`
