### ISSUE TITLE
[Feature Request] Regexp prefix in CommandClient

### ISSUE THREAD

**Issue by Oliver-makes-code** [harmonyland/harmony#306]
**What do you want to request?**
I would like to use a regular expression in the prefix of a CommandClient

**Do you have anything to tell us about your request?**
Using a regexp as the prefix would allow for easier iteration through different combinations of characters, and would allow more complex prefixes.

**Comment by MierenManz** [comment]
I don't think it's a bad idea but why wouldn't `["!", "#", "#$$$!#$%#%"]` etc work for prefixes?

**Comment by nebulatgs** [comment]
> I don't think it's a bad idea but I am curious why `["!", "#", "#$$$!#$%#%"]` etc wouldn't work for prefixes?

Regex is more expressive, and a great fit for prefixes, they allow for very specific triggers, etc.

**Comment by Oliver-makes-code** [comment]
> > I don't think it's a bad idea but I am curious why `["!", "#", "#$$$!#$%#%"]` etc wouldn't work for prefixes?
> 
> Regex is more expressive, and a great fit for prefixes, they allow for very specific triggers, etc.

It also allows for multiple different prefixes using the same base. Having `pf[!?;>]` is much smaller than `["pf?","pf!","pf;","pf>"]

**Comment by Blocksnmore** [comment]
Although this would be nice, I don’t really think its needed at the moment. You can just use a .map statement for what you provided as an example

**Comment by MierenManz** [comment]
@DjDeveloper or @Helloyunho what do you think? Useful feature?

**Comment by Helloyunho** [comment]
> @djdeveloper or @Helloyunho what do you think? Useful feature?

yes if you have message intent enabled

**Comment by Helloyunho** [comment]
closing
