### ISSUE TITLE
[Bug] Embed messages don't get replied to unless undefined

### ISSUE THREAD

**Issue by Blocksnmore** [harmonyland/harmony#309]
**What's the bug?**

When you reply to a message with an embed it won't reply unless the first argument passed is `undefined`
**How do we reproduce it?**
1. Run the following 3 snippets: 
    - `ctx.message.reply(new Embed({"title":"Example embed","description":"Testing"}));`
    - `ctx.message.reply({ embeds: [new Embed({"title":"Example embed","description":"Testing"})]});`
    - `ctx.message.reply(undefined, { embeds: [new Embed({"title":"Example embed","description":"Testing"})]});`
1. Notice that only the last one replies to the message

**What should have happened?**
All 3 should have replied to the message
**What is actually happening?**
The bot only replies to the last message

**What versions you're using?**
 - OS: Manjaro linux x86 Kernel 5.15.19-1-MANJARO 
 - Deno: 1.16.2 (Also tested on 1.18.1)
 - Harmony: 2.5.1

**Do you have anything to tell us more about the bug?**
No

**Comment by Helloyunho** [comment]
about 1 year passed and finally fixed this bug... check f9bbc7902773b70bf5b123bcfdebcc905e447a81
