### ISSUE TITLE
[Feature Request] Add Guilded API support

### ISSUE THREAD

**Issue by Blocksnmore** [harmonyland/harmony#329]
**What do you want to request?**
Guilded API support

**Do you have any solutions?**
If you have, please tell us so we can add(or at least think about) your solution!
Guilded has similar naming to discord when it comes to features such as embed and webhooks, a check could be implemented to switch between logic depending on your platform

**Do you have anything to tell us about your request?**
It would be helpful for developers if they would be able to run a guilded bot using the same codebase as a discord one.

**Comment by quick007** [comment]
I belive that this would be a great addition to harmony support it. Thumbs up from me!

**Comment by MierenManz** [comment]
I don't think it's a good idea to add it to this repo. Mostly because it would mean that we would be dealing with even more complexity. Maybe better to have it in a different repo

**Comment by invalidCards** [comment]
There isn't a Discord library in the world that also supports Slack because it would be a hell of a mess having the two combined, and the same goes for Guilded. Having a separate lib for that makes way more sense than shoehorning it into the current codebase.

**Comment by MierenManz** [comment]
> shoehorning it into the current codebase.

Especially with harmony code base sometimes 😅

**Comment by DjDeveloperr** [comment]
Guilded support is out of scope for this project.

**Comment by Helloyunho** [comment]
Maybe later when harmony gets v3 release we'll consider about it

Right now we're doing v3 project and we want to finish this as soon as possible
