### ISSUE TITLE
[Bug] InteractionUser.discriminator === 0?

### ISSUE THREAD

**Issue by 7xa5h** [harmonyland/harmony#352]
**What's the bug?**
InteractionUser.discriminator always produces #0 even if the user doesnt have the username update.
![image](https://github.com/harmonyland/harmony/assets/119355463/02910f78-eafb-4589-82d0-2178bb9f51c1)
![image](https://github.com/harmonyland/harmony/assets/119355463/e6fd7c15-6c56-4afd-86e9-be2cfbb4a630)
![image](https://github.com/harmonyland/harmony/assets/119355463/0099f6a8-1332-4431-a722-47b7d9f8051b)

**How do we reproduce it?**
What i did is made a new slash command with a user option, thn in the run code i do
```ts 
const user = i.options("user") as InteractionUser
i.reply(`Hello ${user}`)
```

**What should have happened?**
It shouldve only said 0 for the new username

**What is actually happening?**
It says 0 for basically every username?

**What versions you're using?**
 - OS: Windows 10 - Tiny 11
 - Deno: 1.34.2
 - Harmony: 2.8.0

**Comment by Helloyunho** [comment]
I can't reproduce this bug... Can you try with the latest commit(`import harmony from 'https://raw.githubusercontent.com/harmonyland/harmony/main/mod.ts'`)?

**Comment by 7xa5h** [comment]
> import harmony from 'https://raw.githubusercontent.com/harmonyland/harmony/main/mod.ts

for some reason it now works lmao (without the latest version either js 2.8.0?)
it was prob a local bug for me or my discord client or sumn idk but thanks!

**Comment by 7xa5h** [comment]
.
