### ISSUE TITLE
Voice support

### ISSUE THREAD

**Issue by AkiaCode** [harmonyland/harmony#48]
https://discord.com/developers/docs/topics/voice-connections

**Comment by AkiaCode** [comment]
How about making rust for better performance?

**Comment by AkiaCode** [comment]
#86

**Comment by DjDeveloperr** [comment]
@AkiaCode this is different one -- for Voice (UDP) and Sharding (WS), while that issue is for tracking REST Implementation.

**Comment by AkiaCode** [comment]
> @AkiaCode this is different one -- for Voice (UDP) and Sharding (WS), while that issue is for tracking REST Implementation.

Oops, Okay

**Comment by AkiaCode** [comment]
Sharding: #93

**Comment by Cormanz** [comment]
How's progress on this?

**Comment by MierenManz** [comment]
Right now dj got a working repo on https://github.com/harmonyland/harmony_voice
It just needs some additional clean up and then needs to be implemented.

Idk if @DjDeveloperr wants to do the implementation on his own or if he is fine with reviewing a pr for it.
